== C4

C4 offers different levels of abstracted views on a system.

What are these 4 levels - And what can they do?

=== Which levels

1. System Context
2. Containers
3. Components
4. Code

=== Why 4 Levels?

[%step]
Every software system has different stakeholders.
Different needs / aspects of a system can be displayed.



=== https://www.dandoescode.com/blog/c4-models-with-structurizr#level-1-system-context-diagram[System context]

This describes 
[%step]
* The system your're dealing with
* External system it relies upon
* Users of the system: human and non human

=== https://www.dandoescode.com/blog/c4-models-with-structurizr#level-2-container-diagram[Containers]

This lists the major building blocks like

[%step]
* Appplications (VMs, SPAs, Messaging)
* Processes
* Datastores (S3, [No]SQL DBs...)

and their relationships

[.notes]
--
Containers are usullay things that can be deployed individually
--
=== Components

=== Code

=== Structurizr
Structurizr gives us two things:

[%step]
* a DSL to write down our C4 model and
* tools to generate views on this model





=== Environment Drift
Having a local dev setup as close as possible to production has a significant number of advantages

=== Predictability
Containers include everything your application needs.   
Let it be app binaries, libs, config files.   
Except the operating system.

=== Encapsulation
A container should deal with a well defined context - a domain.

=== Dependencies
Resources needed by a container are described in a declarative way.   
Different execution envs require different cfg values. Containers can be configured in different ways to match those requirements without changing a single of app code

=== Testability
Nature of declarative configuration has it that it is easy to test a container in different scenarios. Lets say to simulate slow or failing network connections, different runtimes or JDKs.


=== Links
* https://www.netapp.com/devops-solutions/what-are-containers/[What are containers]
